In [1]:
import array
L=list(range(10))
A=array.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
type(A)

array.array

In [3]:
import numpy as np
np.eye

<function numpy.lib.twodim_base.eye>

In [4]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [5]:
np.empty(3)

array([4.55695127e-303, 1.31353237e-308, 1.33360293e+241])

In [6]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [7]:
np.arange(3).reshape(3,3)

ValueError: cannot reshape array of size 3 into shape (3,3)

In [8]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [9]:
np.arange(9).reshape(3,3) 2**2

SyntaxError: invalid syntax (<ipython-input-9-4cb807c5bffc>, line 1)

In [10]:
x = np.arange(9).reshape(3,3)
x**2

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]], dtype=int32)

In [11]:
x = np.arange(9).reshape(3,3)
2**x

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]], dtype=int32)

In [13]:
y = np.arange(5)
y

array([0, 1, 2, 3, 4])

In [17]:
print("  y =", y)
print("y+5=",y + 5)
print("y*5=", y*5 )
print("y/5=",y/5)
print("y-5=",y -5)
print("y^2=",y**2)

  y = [0 1 2 3 4]
y+5= [5 6 7 8 9]
y*5= [ 0  5 10 15 20]
y/5= [0.  0.2 0.4 0.6 0.8]
y-5= [-5 -4 -3 -2 -1]
y^2= [ 0  1  4  9 16]


In [23]:
theta=np.linspace(0,np.pi,3)

In [24]:
print("theta = ", theta)
print("sin(theta) = ", np.sin(theta))
print("cos(theta = ) "), np.cos(theta)
print("tan(theta) = ", np.tan(theta))

theta =  [0.         1.57079633 3.14159265]
sin(theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta = ) 
tan(theta) =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [25]:
#exponents
z = [1,2,3]
print("z = ", z)
print("e^z = ", np.exp(z))
print("2^z = ", np.exp2(z))
print("3^z = ", np.power(3,z))

z =  [1, 2, 3]
e^z =  [ 2.71828183  7.3890561  20.08553692]
2^z =  [2. 4. 8.]
3^z =  [ 3  9 27]


In [26]:
val=np.empty(3)

In [27]:
val

array([2., 4., 8.])

In [28]:
print(np.empty(5))

[0.  0.2 0.4 0.6 0.8]


In [29]:
print(np.empty(2))

[1.63312394e+16 1.22464680e-16]


In [30]:
print(np.empty(4))

[0.2 0.4 0.6 0.8]


In [31]:
empty?

Object `empty` not found.


In [32]:
np.empty?