In [1]:
import numpy
numpy.__version__

'1.14.2'

In [2]:
import numpy as np

In [3]:
np.__version__

'1.14.2'

In [14]:
result=0;
for i in range(50):
    result +=i
print(result)

1225


In [16]:
L = list(range(5))
L

[0, 1, 2, 3, 4]

In [18]:
type(L[0])

int

In [19]:
L2= [str(c) for c in L]
L2

['0', '1', '2', '3', '4']

In [21]:
type(L2[0])

str

In [22]:
L3=[True, "2",3.0,4]
[type(item) for item in L3]

[bool, str, float, int]

In [23]:
np.array([34,10,78,23,65])

array([34, 10, 78, 23, 65])

In [24]:
#nested list result in multidimensional arrays
np.array([range(i, i + 5) for i in [10, 15, 20]])

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [25]:
#range from 0 to 50 with steps of 10
np.arange(0,50,10)

array([ 0, 10, 20, 30, 40])

In [1]:
np?

Object `np` not found.
